-- GENERATED FILE — do not edit by hand.
-- Regenerate with: node scripts/generate-exercise-seed.mjs
-- Seeds the `exercises` catalog table (see src-tauri/schema.sql). Idempotent:
-- INSERT OR IGNORE leaves existing rows untouched, so it is safe to run on
-- every app start as well as on a fresh db:reset.

INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233182.svg', 'Exercise 1', 'exercise', '/exercise/exercise-8233182.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233183.svg', 'Exercise 2', 'exercise', '/exercise/exercise-8233183.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233184.svg', 'Exercise 3', 'exercise', '/exercise/exercise-8233184.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233185.svg', 'Exercise 4', 'exercise', '/exercise/exercise-8233185.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233186.svg', 'Exercise 5', 'exercise', '/exercise/exercise-8233186.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233187.svg', 'Exercise 6', 'exercise', '/exercise/exercise-8233187.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233188.svg', 'Exercise 7', 'exercise', '/exercise/exercise-8233188.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233189.svg', 'Exercise 8', 'exercise', '/exercise/exercise-8233189.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233190.svg', 'Exercise 9', 'exercise', '/exercise/exercise-8233190.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233191.svg', 'Exercise 10', 'exercise', '/exercise/exercise-8233191.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233192.svg', 'Exercise 11', 'exercise', '/exercise/exercise-8233192.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233193.svg', 'Exercise 12', 'exercise', '/exercise/exercise-8233193.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233194.svg', 'Exercise 13', 'exercise', '/exercise/exercise-8233194.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233195.svg', 'Exercise 14', 'exercise', '/exercise/exercise-8233195.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233196.svg', 'Exercise 15', 'exercise', '/exercise/exercise-8233196.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233197.svg', 'Exercise 16', 'exercise', '/exercise/exercise-8233197.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233198.svg', 'Exercise 17', 'exercise', '/exercise/exercise-8233198.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233199.svg', 'Exercise 18', 'exercise', '/exercise/exercise-8233199.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233200.svg', 'Exercise 19', 'exercise', '/exercise/exercise-8233200.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233201.svg', 'Exercise 20', 'exercise', '/exercise/exercise-8233201.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233202.svg', 'Exercise 21', 'exercise', '/exercise/exercise-8233202.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233203.svg', 'Exercise 22', 'exercise', '/exercise/exercise-8233203.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233204.svg', 'Exercise 23', 'exercise', '/exercise/exercise-8233204.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233205.svg', 'Exercise 24', 'exercise', '/exercise/exercise-8233205.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233206.svg', 'Exercise 25', 'exercise', '/exercise/exercise-8233206.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233207.svg', 'Exercise 26', 'exercise', '/exercise/exercise-8233207.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233208.svg', 'Exercise 27', 'exercise', '/exercise/exercise-8233208.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233209.svg', 'Exercise 28', 'exercise', '/exercise/exercise-8233209.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233210.svg', 'Exercise 29', 'exercise', '/exercise/exercise-8233210.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233211.svg', 'Exercise 30', 'exercise', '/exercise/exercise-8233211.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233212.svg', 'Exercise 31', 'exercise', '/exercise/exercise-8233212.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233213.svg', 'Exercise 32', 'exercise', '/exercise/exercise-8233213.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233214.svg', 'Exercise 33', 'exercise', '/exercise/exercise-8233214.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233215.svg', 'Exercise 34', 'exercise', '/exercise/exercise-8233215.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233216.svg', 'Exercise 35', 'exercise', '/exercise/exercise-8233216.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233217.svg', 'Exercise 36', 'exercise', '/exercise/exercise-8233217.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233218.svg', 'Exercise 37', 'exercise', '/exercise/exercise-8233218.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233219.svg', 'Exercise 38', 'exercise', '/exercise/exercise-8233219.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233220.svg', 'Exercise 39', 'exercise', '/exercise/exercise-8233220.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233221.svg', 'Exercise 40', 'exercise', '/exercise/exercise-8233221.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233222.svg', 'Exercise 41', 'exercise', '/exercise/exercise-8233222.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233223.svg', 'Exercise 42', 'exercise', '/exercise/exercise-8233223.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233224.svg', 'Exercise 43', 'exercise', '/exercise/exercise-8233224.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233225.svg', 'Exercise 44', 'exercise', '/exercise/exercise-8233225.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233226.svg', 'Exercise 45', 'exercise', '/exercise/exercise-8233226.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233227.svg', 'Exercise 46', 'exercise', '/exercise/exercise-8233227.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233228.svg', 'Exercise 47', 'exercise', '/exercise/exercise-8233228.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233229.svg', 'Exercise 48', 'exercise', '/exercise/exercise-8233229.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233230.svg', 'Exercise 49', 'exercise', '/exercise/exercise-8233230.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233231.svg', 'Exercise 50', 'exercise', '/exercise/exercise-8233231.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233232.svg', 'Exercise 51', 'exercise', '/exercise/exercise-8233232.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233233.svg', 'Exercise 52', 'exercise', '/exercise/exercise-8233233.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('exercise-8233234.svg', 'Exercise 53', 'exercise', '/exercise/exercise-8233234.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('adho-mukha-svanasana-4733988.svg', 'Adho Mukha Svanasana', 'yoga', '/yoga-poses/adho-mukha-svanasana-4733988.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('adho-mukha-vrksasana-4699208.svg', 'Adho Mukha Vrksasana', 'yoga', '/yoga-poses/adho-mukha-vrksasana-4699208.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('agnistambhasana-4777340.svg', 'Agnistambhasana', 'yoga', '/yoga-poses/agnistambhasana-4777340.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('ananda-balasana-4777356.svg', 'Ananda Balasana', 'yoga', '/yoga-poses/ananda-balasana-4777356.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('anjaneyasana-4733972.svg', 'Anjaneyasana', 'yoga', '/yoga-poses/anjaneyasana-4733972.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('anjaneyasana-4827429.svg', 'Anjaneyasana', 'yoga', '/yoga-poses/anjaneyasana-4827429.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('ardha-chandrasana-4733982.svg', 'Ardha Chandrasana', 'yoga', '/yoga-poses/ardha-chandrasana-4733982.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('ardha-hanumanasana-4733961.svg', 'Ardha Hanumanasana', 'yoga', '/yoga-poses/ardha-hanumanasana-4733961.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('ardha-pincha-mayurasana-4777344.svg', 'Ardha Pincha Mayurasana', 'yoga', '/yoga-poses/ardha-pincha-mayurasana-4777344.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('ardha-salabhasana-4777350.svg', 'Ardha Salabhasana', 'yoga', '/yoga-poses/ardha-salabhasana-4777350.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('ardha-ustrasana-4733975.svg', 'Ardha Ustrasana', 'yoga', '/yoga-poses/ardha-ustrasana-4733975.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('astavakrasana-4733974.svg', 'Astavakrasana', 'yoga', '/yoga-poses/astavakrasana-4733974.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('baddha-konasana-4827433.svg', 'Baddha Konasana', 'yoga', '/yoga-poses/baddha-konasana-4827433.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('baddha-virabhadrasana-4699215.svg', 'Baddha Virabhadrasana', 'yoga', '/yoga-poses/baddha-virabhadrasana-4699215.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('bakasana-4733979.svg', 'Bakasana', 'yoga', '/yoga-poses/bakasana-4733979.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('balasana-4733985.svg', 'Balasana', 'yoga', '/yoga-poses/balasana-4733985.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('bharadvajasana-4827437.svg', 'Bharadvajasana', 'yoga', '/yoga-poses/bharadvajasana-4827437.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('bhujangasana-4777342.svg', 'Bhujangasana', 'yoga', '/yoga-poses/bhujangasana-4777342.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('bhujapidasana-4699222.svg', 'Bhujapidasana', 'yoga', '/yoga-poses/bhujapidasana-4699222.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('bitilasana-4777343.svg', 'Bitilasana', 'yoga', '/yoga-poses/bitilasana-4777343.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('camatkarasana-4699223.svg', 'Camatkarasana', 'yoga', '/yoga-poses/camatkarasana-4699223.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('chaturanga-dandasana-4699214.svg', 'Chaturanga Dandasana', 'yoga', '/yoga-poses/chaturanga-dandasana-4699214.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('dandayamana-dhanurasana-4733986.svg', 'Dandayamana Dhanurasana', 'yoga', '/yoga-poses/dandayamana-dhanurasana-4733986.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('dhanurasana-4733990.svg', 'Dhanurasana', 'yoga', '/yoga-poses/dhanurasana-4733990.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('eka-pada-koundinyasana-4733987.svg', 'Eka Pada Koundinyasana', 'yoga', '/yoga-poses/eka-pada-koundinyasana-4733987.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('eka-pada-utkatasana-4777347.svg', 'Eka Pada Utkatasana', 'yoga', '/yoga-poses/eka-pada-utkatasana-4777347.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('garudasana-4733991.svg', 'Garudasana', 'yoga', '/yoga-poses/garudasana-4733991.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('gomukhasana-4699211.svg', 'Gomukhasana', 'yoga', '/yoga-poses/gomukhasana-4699211.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('halasana-4733970.svg', 'Halasana', 'yoga', '/yoga-poses/halasana-4733970.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('hanumanasana-4733962.svg', 'Hanumanasana', 'yoga', '/yoga-poses/hanumanasana-4733962.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('janusirsasana-4777349.svg', 'Janusirsasana', 'yoga', '/yoga-poses/janusirsasana-4777349.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('kapotasana-4733983.svg', 'Kapotasana', 'yoga', '/yoga-poses/kapotasana-4733983.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('lolasana-4827430.svg', 'Lolasana', 'yoga', '/yoga-poses/lolasana-4827430.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('makara-adho-mukha-svanasana-4827426.svg', 'Makara Adho Mukha Svanasana', 'yoga', '/yoga-poses/makara-adho-mukha-svanasana-4827426.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('malasana-4777338.svg', 'Malasana', 'yoga', '/yoga-poses/malasana-4777338.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('marjariasana-4777345.svg', 'Marjariasana', 'yoga', '/yoga-poses/marjariasana-4777345.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('matsyasana-4699226.svg', 'Matsyasana', 'yoga', '/yoga-poses/matsyasana-4699226.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('matsyendrasana-4777353.svg', 'Matsyendrasana', 'yoga', '/yoga-poses/matsyendrasana-4777353.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('navasana-4733971.svg', 'Navasana', 'yoga', '/yoga-poses/navasana-4733971.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('pada-adho-mukha-svanasana-4699221.svg', 'Pada Adho Mukha Svanasana', 'yoga', '/yoga-poses/pada-adho-mukha-svanasana-4699221.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('padahastasana-4733976.svg', 'Padahastasana', 'yoga', '/yoga-poses/padahastasana-4733976.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('padangusthasana-4827432.svg', 'Padangusthasana', 'yoga', '/yoga-poses/padangusthasana-4827432.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('parivrtta-trikonasana-4733968.svg', 'Parivrtta Trikonasana', 'yoga', '/yoga-poses/parivrtta-trikonasana-4733968.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('parsva-bakasana-4733977.svg', 'Parsva Bakasana', 'yoga', '/yoga-poses/parsva-bakasana-4733977.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('parsva-balasana-4733981.svg', 'Parsva Balasana', 'yoga', '/yoga-poses/parsva-balasana-4733981.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('parsvottanasana-4699224.svg', 'Parsvottanasana', 'yoga', '/yoga-poses/parsvottanasana-4699224.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('paschimottanasana-4777354.svg', 'Paschimottanasana', 'yoga', '/yoga-poses/paschimottanasana-4777354.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('pavanamuktasana-4733992.svg', 'Pavanamuktasana', 'yoga', '/yoga-poses/pavanamuktasana-4733992.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('phalakasana-4699220.svg', 'Phalakasana', 'yoga', '/yoga-poses/phalakasana-4699220.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('prasarita-padottanasana-4777355.svg', 'Prasarita Padottanasana', 'yoga', '/yoga-poses/prasarita-padottanasana-4777355.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('salabhasana-4777351.svg', 'Salabhasana', 'yoga', '/yoga-poses/salabhasana-4777351.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('salamba-bhujangasana-4777339.svg', 'Salamba Bhujangasana', 'yoga', '/yoga-poses/salamba-bhujangasana-4777339.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('sarvangasana-4699218.svg', 'Sarvangasana', 'yoga', '/yoga-poses/sarvangasana-4699218.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('sasakasana-4827424.svg', 'Sasakasana', 'yoga', '/yoga-poses/sasakasana-4827424.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('setu-bandha-sarvangasana-4827428.svg', 'Setu Bandha Sarvangasana', 'yoga', '/yoga-poses/setu-bandha-sarvangasana-4827428.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('shavasana-4777348.svg', 'Shavasana', 'yoga', '/yoga-poses/shavasana-4777348.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('sirsasana-4699212.svg', 'Sirsasana', 'yoga', '/yoga-poses/sirsasana-4699212.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('skandasana-4733964.svg', 'Skandasana', 'yoga', '/yoga-poses/skandasana-4733964.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('sukhasana-4827436.svg', 'Sukhasana', 'yoga', '/yoga-poses/sukhasana-4827436.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('supta-kapotasana-4733984.svg', 'Supta Kapotasana', 'yoga', '/yoga-poses/supta-kapotasana-4733984.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('supta-matsyendrasana-4827425.svg', 'Supta Matsyendrasana', 'yoga', '/yoga-poses/supta-matsyendrasana-4827425.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('svarga-dvijasana-4827434.svg', 'Svarga Dvijasana', 'yoga', '/yoga-poses/svarga-dvijasana-4827434.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('tadasana-4777337.svg', 'Tadasana', 'yoga', '/yoga-poses/tadasana-4777337.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('tittibhasana-4827435.svg', 'Tittibhasana', 'yoga', '/yoga-poses/tittibhasana-4827435.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('tri-pad-adho-mukha-svanasana-4699225.svg', 'Tri Pad Adho Mukha Svanasana', 'yoga', '/yoga-poses/tri-pad-adho-mukha-svanasana-4699225.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('trikonasana-4733965.svg', 'Trikonasana', 'yoga', '/yoga-poses/trikonasana-4733965.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('urdhva-dhanurasana-4733967.svg', 'Urdhva Dhanurasana', 'yoga', '/yoga-poses/urdhva-dhanurasana-4733967.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('urdhva-mukha-svanasana-4699210.svg', 'Urdhva Mukha Svanasana', 'yoga', '/yoga-poses/urdhva-mukha-svanasana-4699210.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('urdhva-prasarita-eka-padasana-4827427.svg', 'Urdhva Prasarita Eka Padasana', 'yoga', '/yoga-poses/urdhva-prasarita-eka-padasana-4827427.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('ustrasana-4733973.svg', 'Ustrasana', 'yoga', '/yoga-poses/ustrasana-4733973.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('utkata-konasana-4699217.svg', 'Utkata Konasana', 'yoga', '/yoga-poses/utkata-konasana-4699217.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('utkatasana-4777346.svg', 'Utkatasana', 'yoga', '/yoga-poses/utkatasana-4777346.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('uttana-shishosana-4733969.svg', 'Uttana Shishosana', 'yoga', '/yoga-poses/uttana-shishosana-4733969.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('uttanasana-4827431.svg', 'Uttanasana', 'yoga', '/yoga-poses/uttanasana-4827431.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('utthan-pristhasana-4733978.svg', 'Utthan Pristhasana', 'yoga', '/yoga-poses/utthan-pristhasana-4733978.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('utthita-hasta-padangusthasana-4733966.svg', 'Utthita Hasta Padangusthasana', 'yoga', '/yoga-poses/utthita-hasta-padangusthasana-4733966.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('utthita-parsvakonasana-4733980.svg', 'Utthita Parsvakonasana', 'yoga', '/yoga-poses/utthita-parsvakonasana-4733980.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('utthita-tadasana-4733989.svg', 'Utthita Tadasana', 'yoga', '/yoga-poses/utthita-tadasana-4733989.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('vasisthasana-4777352.svg', 'Vasisthasana', 'yoga', '/yoga-poses/vasisthasana-4777352.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('viparita-karani-4777341.svg', 'Viparita Karani', 'yoga', '/yoga-poses/viparita-karani-4777341.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('viparita-virabhadrasana-4699219.svg', 'Viparita Virabhadrasana', 'yoga', '/yoga-poses/viparita-virabhadrasana-4699219.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('virabhadrasana-4699209.svg', 'Virabhadrasana', 'yoga', '/yoga-poses/virabhadrasana-4699209.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('virabhadrasana-4699213.svg', 'Virabhadrasana', 'yoga', '/yoga-poses/virabhadrasana-4699213.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('virabhadrasana-4699216.svg', 'Virabhadrasana', 'yoga', '/yoga-poses/virabhadrasana-4699216.svg');
INSERT OR IGNORE INTO exercises (id, name, category, src) VALUES ('vriksasana-4733963.svg', 'Vriksasana', 'yoga', '/yoga-poses/vriksasana-4733963.svg');
